### ISSUE TITLE
Support --dev & --prod flags

### ISSUE THREAD

**Issue by rayshan** [geekjuice/npmlist#4]
https://github.com/npm/npm/releases/tag/v2.7.0

**Comment by geekjuice** [comment]
Oh that's awesome. I definitely need to update this tool to use the (finally working) native `npm ls --depth=0`. I'll try to add this feature as well and possibly handle the two cases differently e.g. List the directory of the linked projects when using `--dev` flag.

**Comment by rayshan** [comment]
thanks! use this daily and still works well
