### ISSUE TITLE
No packages found

### ISSUE THREAD

**Issue by eugenesvk** [geekjuice/npmlist#8]
I've just installed your package with node v5.9.1 and Windows 10 and it can't find any packages, local or global, in all cases it outputs this error in command prompt
```
Installed npm packages: (global)
No packages found.
```
even though npm list works fine

**Comment by geekjuice** [comment]
Do you mind posting your output to `npm list --depth=0` or `npm list --global --depth=0`? There might be an edge case I haven't accounted for in the parser.

**Comment by eugenesvk** [comment]
Sure,
```
> npm list --depth=0
jupyter-nodejs@1.1.0 C:\Dev\_TestCharts\jupyter-nodejs-1.1.0\package
+-- async@0.9.2
+-- babel@5.8.38
+-- bencode@0.7.0
+-- coffee-script@1.10.0
+-- contextify@0.1.15
+-- mkdirp@0.5.1
+-- superagent@1.8.3
`-- zmq@2.14.0
```

```
> npm list --global --depth=0

c:\Dev\Node.js\bin
+-- angular2@2.0.0-beta.13
+-- bower@1.7.7
+-- browserify@13.0.0
+-- chartist@0.9.7
+-- UNMET PEER DEPENDENCY es6-shim@^0.35.0
+-- fs-extra@0.26.7
+-- gulp@3.9.1
+-- ijavascript@5.0.11-beta.0
+-- jscs@2.11.0
+-- jshint@2.9.1
+-- karma@0.13.22
+-- karma-browserify@5.0.3
+-- karma-chrome-launcher@0.2.3
+-- karma-cli@0.1.2
+-- karma-custom@1.1.9
+-- karma-custom-reporter@1.0.0
+-- nan@2.2.0
+-- node-gyp@3.3.1
+-- npm@3.8.3
+-- npmlist@3.1.0
+-- nw@0.14.0-rc2sdk
+-- nw-gyp@0.13.0
+-- phantomjs2@2.2.0
+-- plotly-notebook-js@0.1.2
+-- plotly.js@1.7.0
+-- UNMET PEER DEPENDENCY reflect-metadata@0.1.2
+-- UNMET PEER DEPENDENCY rxjs@5.0.0-beta.2
+-- watchify@3.7.0
`-- UNMET PEER DEPENDENCY zone.js@^0.6.6

npm ERR! peer dep missing: es6-shim@^0.35.0, required by angular2@2.0.0-beta.13
npm ERR! peer dep missing: reflect-metadata@0.1.2, required by angular2@2.0.0-beta.13
npm ERR! peer dep missing: rxjs@5.0.0-beta.2, required by angular2@2.0.0-beta.13
npm ERR! peer dep missing: zone.js@^0.6.6, required by angular2@2.0.0-beta.13
```

**Comment by geekjuice** [comment]
Ah... `npmlist` looks for `├` when parsing but your setup seems to be using `+-`. I'll try to find some time to update this, but in the meantime, it may just be worth using `npm list` directly.

**Comment by eugenesvk** [comment]
How do I change to `├`? That's what I got by default so would be nice to have it supported. I hate that I have to add the 0 depth to npm list  thought, but yeah, will use it in the meantime.

**Comment by geekjuice** [comment]
Just published `3.1.1` which should be able to parse out the examples you provided.

**Comment by eugenesvk** [comment]
Thanks for a prompt fix! That mostly works except for 
```
`-- zmq@2.14.0
```
Would you kindly add this (backtick double hyphen) to the mix as well?

**Comment by geekjuice** [comment]
:grimacing: So close... `3.1.2` published.

**Comment by eugenesvk** [comment]
Thank you! Works now even with those last backticked packages!
By the way, I couldn't update it automatically with `npm update -g npmlist`. Don't know enough about how npm does it to understand whether this is some package settings that you have to adjust or just a quirk of  my system.
For some reason the `wanted` version is not latest here (I thought that only made sense for local packages listed in `package.json`)

```
> npm outdated -g --depth=0
Package        Current         Wanted   Latest  Location
npmlist          3.1.1          3.1.1    3.1.2
```

**Comment by geekjuice** [comment]
Hmm, is this still an issue? May have been a caching issue as I can't seem to reproduce it on my end.

**Comment by eugenesvk** [comment]
Nope, I've uninstalled and installed again — got the latest version. Just wanted to flag it in case there is something wrong with the package.
